CREATE TABLE td_test_dataset_b.EMPLOYEE (
	FIRSTNAME VARCHAR(100) NOT CASESPECIFIC,
	LASTNAME VARCHAR(100) NOT CASESPECIFIC,
	DOB DATE
);

CREATE TABLE td_test_dataset_a.PROJECT (
	PROJECTNAME VARCHAR(100),
	EMPLOYEEFIRSTNAME VARCHAR(100) NOT CASESPECIFIC
);

SELECT
	UPPER(FIRSTNAME),
	DOB
	FROM EMPLOYEE e
	JOIN PROJECT p
		on e.FIRSTNAME = p.EMPLOYEEFIRSTNAME;
